### ISSUE TITLE
context.log is not a function

### ISSUE THREAD

**Issue by ratancs** [flxbe/strider-aws-codedeploy#7]
https://github.com/flxbe/strider-aws-codedeploy/blob/38acf119f627eb2604170cfb2e9d8162f750dc0d/tasks/index.js#L190

**Comment by flxbe** [comment]
Very strange. I will look right into it. Which version of strider do you use?

**Comment by flxbe** [comment]
Seems like `context.log` is no longer supported. I removed this kind of logs completely since it was only there for dev-purposes. The issue should be solved.

You can either directly install the new plugin version as a git-repository or wait until the new version shows up in the plugin list. Either way, I hope this solves your issue.

1a56089cf63b76f0ef7948ef4fc6547eeb3a65e5
